### PR TITLE
New Angular 9 Template

### PR DESCRIPTION
**Pull request by BaileyJM02**
This commit includes a simple Angular 9 template for Jexia

### CODE REVIEW

**Comment by BaileyJM02** [comment]
Hi @MishaJexia, any update on the merge? :smile:

**Comment by MishaJexia** [comment]
Hi, can you add jexia-js-sdk, please?

**Comment by BaileyJM02** [comment]
Sure, what functionality would you like it to perform?

**Comment by MishaJexia** [comment]
Maybe a basic one.
Just add jexia-sdk-sd into dependency and, maybe basic CRUD (if possible).

**Comment by BaileyJM02** [comment]
Hi @MishaJexia, I've added the Jexia SDK and added a little bit of example code in [main.ts](https://github.com/jexia/angular_starting_template/pull/1/files#diff-8cfead41d88ad47d44509a8ab0a109adR20), though I couln't create a full example as it resulted in errors due to not being able to set the credentials.

**Pull request merged**
